name: Java Maven Tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Gets the code from the repo
      - name: Checkout code
        uses: actions/checkout@v4

      # Sets up Java for Maven
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # Runs all tests
      - name: Run Maven tests
        run: mvn test